### PR TITLE
Add a feed-forward term

### PR DESCRIPTION
**Pull request by mzaffalon**
The total control signal (PID + feed-forward) is to be limited by the
integral anti-windup.

### CODE REVIEW

**Comment by mzaffalon** [comment]
I would like to use DiscretePID.jl with a feed-forward contribution: sometimes the sum of the two control inputs (PID and feed-forward) exceeds the actuator range.

**Comment by mzaffalon** [comment]
I didn't expected such a fast review and positive feedback (no pun intendend). Should I rebase squash the commit or do you do it?

**Comment by baggepinnen** [comment]
No worries, I can squash in the web interface! :)

**Comment by mzaffalon** [comment]
Oh, I didn't know one could do that!

**Comment by baggepinnen** [comment]
Thanks for the PR! I will update an unrelated thing that caused tets to fail and then have a new release out ASAP :)

**Pull request merged**
